#default
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/batch4_demo?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
